import { Sparkles, ShoppingBag, ArrowDown, HelpCircle, CloudRain } from "lucide-react";

interface HeroProps {
  onShopNowClick: () => void;
  onOpenConsultation: () => void;
}

export default function Hero({ onShopNowClick, onOpenConsultation }: HeroProps) {
  // We use the image generated by the AI Studio tool
  // const heroImgUrl = "/src/assets/images/hero-image.jpg";
  const heroImgUrl = "../src/assets/images/hero-image.jpg";

  // Create an array for simulated rainfall drops
  const rainDrops = Array.from({ length: 45 }).map((_, i) => ({
    id: i,
    left: `${Math.random() * 100}%`,
    delay: `${Math.random() * 4}s`,
    duration: `${1.5 + Math.random() * 2.5}s`,
    opacity: 0.15 + Math.random() * 0.35,
    length: `${15 + Math.random() * 25}px`,
  }));

  return (
    <section
      id="hero-section"
      className="relative min-h-screen flex items-center justify-center pt-20 overflow-hidden bg-black"
    >
      {/* Background Image Container */}
      <div className="absolute inset-0 z-0">
  {/* Video Player Embed */}
  <iframe
    src="https://player.cloudinary.com/embed/?cloud_name=djh0gmshm&public_id=Meta_AI_2_depgs9&autoplay=true&loop=true&muted=true"
    className="w-full h-full object-cover"
    allow="autoplay; fullscreen"
    frameBorder="0"
    title="Luxury Background Video"
  />

  {/* Gradients overlays jo pehle se the */}
  <div className="absolute inset-0 bg-gradient-to-r from-[#050505] via-[#050505]/95 md:via-[#050505]/80 to-transparent z-10" />
  <div className="absolute inset-0 bg-gradient-to-t from-[#0b0b0b] via-transparent to-black/50 z-10" />
</div>
      

      {/* Realistic Interactive "Raining Gold" particles */}
      <div className="absolute inset-0 pointer-events-none z-20 overflow-hidden">
        {rainDrops.map((drop) => (
          <div
            key={drop.id}
            className="absolute bg-gradient-to-b from-gold-300 to-transparent rounded"
            style={{
              left: drop.left,
              top: "-5%",
              width: "1px",
              height: drop.length,
              opacity: drop.opacity,
              animation: `fall ${drop.duration} linear infinite`,
              animationDelay: drop.delay,
            }}
          />
        ))}
      </div>

      {/* CSS Animation injection */}
      <style>{`
        @keyframes fall {
          0% {
            transform: translateY(-20px) rotate(15deg);
            opacity: 0;
          }
          10% {
            opacity: 0.6;
          }
          90% {
            opacity: 0.4;
          }
          100% {
            transform: translateY(110vh) rotate(15deg);
            opacity: 0;
          }
        }
      `}</style>

      {/* Hero Content Container */}
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full py-12 sm:py-20 z-30">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          
          {/* Left Text Column */}
          <div className="lg:col-span-7 flex flex-col items-start text-left mt-8 sm:mt-12">
            
            {/* Top Badge: Monsoon Magic in Luxury Black-Gold */}
            <div className="flex items-center gap-2 mb-4 animate-bounce duration-[3s]">
              <div className="p-2 bg-gold-950/40 border border-gold-600/50 rounded-full">
                <CloudRain className="w-5 h-5 text-gold-400" />
              </div>
              <div className="flex flex-col">
                <div className="flex items-center gap-1.5">
                  <span className="w-6 h-[1px] bg-gold-500" />
                  <span className="font-sans text-[10px] tracking-[0.4em] text-gold-300 uppercase font-semibold">
                    MONSOON MAGIC
                  </span>
                  <span className="w-6 h-[1px] bg-gold-500" />
                </div>
              </div>
            </div>

            {/* Elegant Main Heading Pair */}
            <div className="relative mb-6">
              <h1 className="font-serif text-5xl sm:text-7xl lg:text-8xl font-medium text-white tracking-tight leading-[0.95] drop-shadow-lg">
                It's Raining
              </h1>
              {/* Cursive Custom-Script "Sale" */}
              <div className="relative -mt-4 sm:-mt-6 ml-8 sm:ml-16 transform -rotate-3">
                <span className="font-script text-7xl sm:text-9xl lg:text-[10rem] text-transparent bg-clip-text bg-gradient-to-r from-gold-300 via-gold-500 to-gold-200 drop-shadow-[0_4px_12px_rgba(197,151,60,0.3)] select-none leading-none">
                  Sale
                </span>
                {/* Visual Accent */}
                <span className="absolute -right-8 top-1/2 -translate-y-1/2 w-8 h-[1px] bg-gold-400/60 hidden sm:block" />
              </div>
            </div>

            {/* Transform Your Home Line */}
            <p className="font-sans text-xs sm:text-sm tracking-[0.3em] text-gold-100 font-medium uppercase mb-8 border-l border-gold-500 pl-4 py-1">
              Transform every corner of your home
            </p>

            {/* Big Interactive Sale Discount Section */}
            <div className="flex flex-wrap items-center gap-6 sm:gap-8 mb-10 py-4 px-6 bg-black/60 border border-gold-900/30 rounded-xl backdrop-blur-sm max-w-xl">
              
              <div className="flex items-center gap-2">
                <div className="flex flex-col text-right">
                  <span className="font-sans text-[10px] tracking-widest text-gold-400 uppercase font-bold">UP TO</span>
                  <span className="font-sans text-lg tracking-widest text-white uppercase font-black">TO</span>
                </div>
                {/* Massive 80% */}
                <span className="font-serif text-6xl sm:text-8xl font-black text-transparent bg-clip-text bg-gradient-to-b from-gold-200 via-gold-400 to-gold-600 tracking-tighter">
                  80%
                </span>
                <span className="font-serif text-4xl sm:text-5xl font-bold text-gold-300">
                  OFF
                </span>
              </div>

              {/* Specs bullet list inside the reference style */}
              <div className="flex flex-col justify-center space-y-1 pl-4 sm:pl-6 border-t sm:border-t-0 sm:border-l border-gold-900/40">
                <div className="flex items-center gap-2 text-[10px] sm:text-xs font-sans tracking-widest text-white uppercase font-medium">
                  <span className="w-1.5 h-1.5 rounded-full bg-gold-400" />
                  HOME DECOR
                </div>
                <div className="flex items-center gap-2 text-[10px] sm:text-xs font-sans tracking-widest text-white uppercase font-medium">
                  <span className="w-1.5 h-1.5 rounded-full bg-gold-400" />
                  BIG SAVINGS
                </div>
                <div className="flex items-center gap-2 text-[10px] sm:text-xs font-sans tracking-widest text-white uppercase font-medium">
                  <span className="w-1.5 h-1.5 rounded-full bg-gold-400" />
                  ACCENT PIECES
                </div>
              </div>

            </div>

            {/* CTA Buttons */}
            <div className="flex flex-wrap items-center gap-4">
              <button
                id="shop-now-hero-btn"
                onClick={onShopNowClick}
                className="group relative px-8 py-4 overflow-hidden rounded-md border border-gold-500 font-sans text-xs uppercase tracking-[0.2em] font-semibold text-black transition-all duration-300 cursor-pointer shadow-lg shadow-gold-950/40"
              >
                {/* Shimmer background */}
                <div className="absolute inset-0 bg-gradient-to-r from-gold-500 via-gold-300 to-gold-600 transition-all duration-500 group-hover:scale-105" />
                <div className="absolute -inset-y-0 -inset-x-12 bg-white/20 skew-x-12 -translate-x-full group-hover:translate-x-full transition-transform duration-1000 ease-out" />
                
                <span className="relative flex items-center gap-2">
                  SHOP NOW
                  <ArrowDown className="w-3.5 h-3.5 transition-transform duration-300 group-hover:translate-y-0.5" />
                </span>
              </button>

              <button
                id="consult-hero-btn"
                onClick={onOpenConsultation}
                className="px-6 py-4 rounded-md border border-neutral-800 bg-neutral-900/60 hover:bg-neutral-900 hover:border-gold-600 text-neutral-300 hover:text-gold-200 font-sans text-xs uppercase tracking-[0.2em] font-semibold transition-all duration-300"
              >
                Free Design Consult
              </button>
            </div>

          </div>

          {/* Right Column (Placeholder on mobile, gives space for background focal point on desktop) */}
          <div className="hidden lg:block lg:col-span-5 h-[400px] pointer-events-none" />

        </div>
      </div>
    </section>
  );
}
